name = "fish-cost-calculator"
main = "worker/index.js"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "app/dist"

[[d1_databases]]
binding = "DB"
database_name = "fish-cost-calculator"
database_id = "997dfe18-7b5f-4c4d-97f4-b84c68b5ee4f"
