/**
 * Neon (Postgres) data-layer adapter.
 *
 * Exposes the DbAdapter interface (shared/db/interface.js) over the Neon
 * serverless pool used by Vercel functions.
 *
 * Module system: ESM — compatible with api/*.js (Vercel serverless, ESM).
 *
 * @module api/_lib/neonDb
 */

import { query } from './db.js';
import { ERR_DUPLICATE_USER } from '../../shared/db/interface.js';

/**
 * Build the Neon DbAdapter (stateless — delegates to the shared Neon pool).
 *
 * @returns {import('../../shared/db/interface.js').DbAdapter}
 */
export function makeNeonAdapter() {
  return {
    /**
     * Find a user by username.
     * @param {string} username
     * @returns {Promise<{id: string|number, username: string, password: string}|null>}
     */
    async findUserByUsername(username) {
      const result = await query(
        'SELECT id, username, password FROM users WHERE username = $1',
        [username]
      );
      return result.rows[0] ?? null;
    },

    /**
     * Create a user.  Translates Postgres unique-constraint violation (23505)
     * to ERR_DUPLICATE_USER so the handler core stays driver-agnostic.
     *
     * @param {string} username
     * @param {string} hashedPassword
     * @returns {Promise<{id: string|number, username: string}>}
     */
    async createUser(username, hashedPassword) {
      try {
        const result = await query(
          'INSERT INTO users (username, password) VALUES ($1, $2) RETURNING id, username',
          [username, hashedPassword]
        );
        return result.rows[0];
      } catch (err) {
        if (err.code === '23505') {
          const dupErr = new Error('Username already exists');
          dupErr.code = ERR_DUPLICATE_USER;
          throw dupErr;
        }
        throw err;
      }
    },

    /**
     * List all saved calculations for a user, ordered by date DESC.
     *
     * @param {string|number} userId
     * @returns {Promise<Array>}
     */
    async listSavedCalcs(userId) {
      const result = await query(
        'SELECT * FROM calculations WHERE user_id = $1 ORDER BY date DESC',
        [userId]
      );
      return result.rows;
    },

    /**
     * Insert a new calculation. The timestamp is generated by Postgres via NOW()
     * — no client-clock date is accepted.
     *
     * @param {string|number} userId
     * @param {{ name, species, product, cost, yield, result }} fields
     * @returns {Promise<{id: string|number}>}
     */
    async saveCalc(userId, fields) {
      const { name, species, product, cost, yield: yieldVal, result } = fields;
      const dbResult = await query(
        `INSERT INTO calculations (user_id, name, species, product, cost, yield, result, date)
         VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
         RETURNING id`,
        [userId, name, species, product, cost, yieldVal, result]
      );
      return dbResult.rows[0];
    },

    /**
     * Find a single calculation by its id. Returns at minimum {id, user_id}.
     *
     * @param {string|number} id
     * @returns {Promise<{id: string|number, user_id: string|number}|null>}
     */
    async findCalcById(id) {
      const result = await query(
        'SELECT id, user_id FROM calculations WHERE id = $1',
        [id]
      );
      return result.rows[0] ?? null;
    },

    /**
     * Delete a calculation by its id.
     * Ownership must be verified by the caller (handler) before calling this.
     *
     * @param {string|number} id
     * @returns {Promise<void>}
     */
    async deleteCalc(id) {
      await query('DELETE FROM calculations WHERE id = $1', [id]);
    },
  };
}
