/**
 * Neon (Postgres) data-layer adapter.
 *
 * Exposes the DbAdapter interface (shared/db/interface.js) over the Neon
 * serverless pool used by Vercel functions.
 *
 * Module system: ESM — compatible with api/*.js (Vercel serverless, ESM).
 *
 * @module api/_lib/neonDb
 */

import { query } from './db.js';
import { ERR_DUPLICATE_USER } from '../../shared/db/interface.js';

/**
 * Build the Neon DbAdapter (stateless — delegates to the shared Neon pool).
 *
 * @returns {import('../../shared/db/interface.js').DbAdapter}
 */
export function makeNeonAdapter() {
  return {
    /**
     * Find a user by username.
     * @param {string} username
     * @returns {Promise<{id: string|number, username: string, password: string}|null>}
     */
    async findUserByUsername(username) {
      const result = await query(
        'SELECT id, username, password FROM users WHERE username = $1',
        [username]
      );
      return result.rows[0] ?? null;
    },

    /**
     * Create a user.  Translates Postgres unique-constraint violation (23505)
     * to ERR_DUPLICATE_USER so the handler core stays driver-agnostic.
     *
     * @param {string} username
     * @param {string} hashedPassword
     * @returns {Promise<{id: string|number, username: string}>}
     */
    async createUser(username, hashedPassword) {
      try {
        const result = await query(
          'INSERT INTO users (username, password) VALUES ($1, $2) RETURNING id, username',
          [username, hashedPassword]
        );
        return result.rows[0];
      } catch (err) {
        if (err.code === '23505') {
          const dupErr = new Error('Username already exists');
          dupErr.code = ERR_DUPLICATE_USER;
          throw dupErr;
        }
        throw err;
      }
    },

    /**
     * List all saved calculations for a user, ordered by date DESC.
     *
     * @param {string|number} userId
     * @returns {Promise<Array>}
     */
    async listSavedCalcs(userId) {
      const result = await query(
        'SELECT * FROM calculations WHERE user_id = $1 ORDER BY date DESC',
        [userId]
      );
      return result.rows;
    },

    /**
     * Insert a new calculation. The timestamp is generated by Postgres via NOW()
     * — no client-clock date is accepted.
     *
     * @param {string|number} userId
     * @param {{ name, species, product, cost, yield, result }} fields
     * @returns {Promise<{id: string|number}>}
     */
    async saveCalc(userId, fields) {
      const { name, species, product, cost, yield: yieldVal, result } = fields;
      const dbResult = await query(
        `INSERT INTO calculations (user_id, name, species, product, cost, yield, result, date)
         VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
         RETURNING id`,
        [userId, name, species, product, cost, yieldVal, result]
      );
      return dbResult.rows[0];
    },

    /**
     * Find a single calculation by its id. Returns at minimum {id, user_id}.
     *
     * @param {string|number} id
     * @returns {Promise<{id: string|number, user_id: string|number}|null>}
     */
    async findCalcById(id) {
      const result = await query(
        'SELECT id, user_id FROM calculations WHERE id = $1',
        [id]
      );
      return result.rows[0] ?? null;
    },

    /**
     * Delete a calculation by its id.
     * Ownership must be verified by the caller (handler) before calling this.
     *
     * @param {string|number} id
     * @returns {Promise<void>}
     */
    async deleteCalc(id) {
      await query('DELETE FROM calculations WHERE id = $1', [id]);
    },

    // -----------------------------------------------------------------------
    // User-data methods
    // -----------------------------------------------------------------------

    /**
     * List all user_data rows for a user.
     *
     * @param {string|number} userId
     * @returns {Promise<Array>}
     */
    async listUserData(userId) {
      const result = await query(
        'SELECT id, species, product, yield, source FROM user_data WHERE user_id = $1',
        [userId]
      );
      return result.rows;
    },

    /**
     * Insert a new user_data row.
     *
     * @param {string|number} userId
     * @param {{ species, product, yield, source }} fields
     * @returns {Promise<{id: string|number}>}
     */
    async createUserData(userId, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      const result = await query(
        'INSERT INTO user_data (user_id, species, product, yield, source) VALUES ($1, $2, $3, $4, $5) RETURNING id',
        [userId, species, product, yieldVal, source]
      );
      return result.rows[0];
    },

    /**
     * Find a single user_data row by id. Returns at minimum {id, user_id}.
     *
     * @param {string|number} id
     * @returns {Promise<{id: string|number, user_id: string|number}|null>}
     */
    async findUserDataById(id) {
      const result = await query(
        'SELECT id, user_id FROM user_data WHERE id = $1',
        [id]
      );
      return result.rows[0] ?? null;
    },

    /**
     * Update a user_data row using SQL COALESCE for partial updates.
     * The caller (handler) passes null for fields to keep unchanged.
     * Ownership must be verified by the caller before this.
     *
     * @param {string|number} id
     * @param {{ species, product, yield, source }} fields  (null = keep current)
     * @returns {Promise<void>}
     */
    async updateUserData(id, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      await query(
        `UPDATE user_data
         SET species = COALESCE($1, species),
             product = COALESCE($2, product),
             yield   = COALESCE($3, yield),
             source  = COALESCE($4, source)
         WHERE id = $5`,
        [species, product, yieldVal, source, id]
      );
    },

    /**
     * Delete a user_data row by id.
     * Ownership must be verified by the caller before this.
     *
     * @param {string|number} id
     * @returns {Promise<void>}
     */
    async deleteUserData(id) {
      await query('DELETE FROM user_data WHERE id = $1', [id]);
    },

    /**
     * Upsert one user_data row: update yield+source if (userId, species, product)
     * already exists; otherwise insert.
     *
     * @param {string|number} userId
     * @param {{ species, product, yield, source }} fields
     * @returns {Promise<{inserted: boolean}>}
     */
    async upsertUserDataRow(userId, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      const existing = await query(
        'SELECT id FROM user_data WHERE user_id = $1 AND LOWER(species) = LOWER($2) AND LOWER(product) = LOWER($3) LIMIT 1',
        [userId, species, product]
      );

      if (existing.rows[0]) {
        await query(
          'UPDATE user_data SET yield = $1, source = $2 WHERE id = $3 AND user_id = $4',
          [yieldVal, source, existing.rows[0].id, userId]
        );
        return { inserted: false };
      } else {
        await query(
          'INSERT INTO user_data (user_id, species, product, yield, source) VALUES ($1, $2, $3, $4, $5)',
          [userId, species, product, yieldVal, source]
        );
        return { inserted: true };
      }
    },

    // -----------------------------------------------------------------------
    // Export methods
    // -----------------------------------------------------------------------

    /**
     * List all user_data rows for export.
     *
     * @param {string|number} userId
     * @returns {Promise<Array>}
     */
    async listUserDataForExport(userId) {
      const result = await query(
        'SELECT * FROM user_data WHERE user_id = $1',
        [userId]
      );
      return result.rows;
    },

    /**
     * List all calculations for export, ordered by date DESC.
     *
     * @param {string|number} userId
     * @returns {Promise<Array>}
     */
    async listCalcsForExport(userId) {
      const result = await query(
        'SELECT * FROM calculations WHERE user_id = $1 ORDER BY date DESC',
        [userId]
      );
      return result.rows;
    },

    // -----------------------------------------------------------------------
    // Public methods (no auth)
    // -----------------------------------------------------------------------

    /**
     * List recent public calculations (no user_id), ordered by date DESC,
     * limited to 100 rows.
     *
     * @returns {Promise<Array>}
     */
    async listPublicCalcs() {
      const result = await query(
        `SELECT id, species, product, cost, yield, result, date
         FROM calculations
         ORDER BY date DESC
         LIMIT 100`
      );
      return result.rows;
    },

    /**
     * List all visible contributors joined with username and contribution_count,
     * ordered by contribution_count DESC.
     *
     * @returns {Promise<Array>}
     */
    async listContributors() {
      const result = await query(
        `SELECT c.*, u.username, COUNT(ud.id) as contribution_count
         FROM contributors c
         JOIN users u ON c.user_id = u.id
         LEFT JOIN user_data ud ON c.user_id = ud.user_id
         WHERE c.show_on_page = true
         GROUP BY c.id, u.username
         ORDER BY contribution_count DESC`
      );
      return result.rows;
    },

    /**
     * Return the full fish-data payload built from three tables:
     *   species, fish_yields, species_profiles.
     *
     * @returns {Promise<{fishData: Object, profiles: Object, source: Object}>}
     */
    async getFishData() {
      const speciesResult = await query(
        `SELECT id, name, scientific_name, category
         FROM species
         ORDER BY category, name`
      );

      const yieldsResult = await query(
        `SELECT species_id, from_state, to_state, yield_percent, range_min, range_max
         FROM fish_yields
         ORDER BY species_id, from_state, to_state`
      );

      const profilesResult = await query(
        `SELECT species_id, description, culinary_uses, edible_portions, url
         FROM species_profiles`
      );

      const fishData = {};
      const profiles = {};
      const speciesMap = {};

      for (const species of speciesResult.rows) {
        speciesMap[species.id] = species;
        fishData[species.name] = {
          scientific_name: species.scientific_name,
          category: species.category,
          conversions: {},
        };
      }

      for (const yieldRow of yieldsResult.rows) {
        const species = speciesMap[yieldRow.species_id];
        if (species && fishData[species.name]) {
          const fromLabel =
            yieldRow.from_state !== 'Round' &&
            yieldRow.from_state !== 'Whole' &&
            yieldRow.from_state !== 'Raw Whole'
              ? `From ${yieldRow.from_state}: `
              : '';
          const label = `${fromLabel}${yieldRow.to_state}`;
          fishData[species.name].conversions[label] = {
            yield: parseFloat(yieldRow.yield_percent),
            range:
              yieldRow.range_min && yieldRow.range_max
                ? [parseFloat(yieldRow.range_min), parseFloat(yieldRow.range_max)]
                : null,
            from: yieldRow.from_state,
            to: yieldRow.to_state,
          };
        }
      }

      for (const profile of profilesResult.rows) {
        const species = speciesMap[profile.species_id];
        if (species) {
          profiles[species.name] = {
            description: profile.description,
            culinary_uses: profile.culinary_uses,
            edible_portions: profile.edible_portions,
            url: profile.url,
          };
        }
      }

      return {
        fishData,
        profiles,
        source: {
          title: 'Recoveries and Yields from Pacific Fish and Shellfish',
          authors: ['Chuck Crapo', 'Brian Paust', 'Jerry Babbitt'],
          publisher: 'Alaska Sea Grant College Program',
          publication: 'Marine Advisory Bulletin No. 37',
          year: 2004,
        },
      };
    },

    // -----------------------------------------------------------------------
    // Contributor profile methods (authenticated)
    // -----------------------------------------------------------------------

    /**
     * Return the contributor profile row for userId, or null if none exists.
     *
     * @param {string|number} userId
     * @returns {Promise<Object|null>}
     */
    async getContributorProfile(userId) {
      const result = await query(
        'SELECT * FROM contributors WHERE user_id = $1',
        [userId]
      );
      return result.rows[0] ?? null;
    },

    /**
     * Upsert a contributor profile.  Returns {id, created} where created is
     * true for an insert, false for an update.
     *
     * @param {string|number} userId
     * @param {{ display_name, organization, bio, show_on_page }} fields
     * @returns {Promise<{id: string|number, created: boolean}>}
     */
    async saveContributorProfile(userId, fields) {
      const { display_name, organization, bio, show_on_page } = fields;
      const existing = await query(
        'SELECT id FROM contributors WHERE user_id = $1',
        [userId]
      );

      if (existing.rows[0]) {
        await query(
          `UPDATE contributors
           SET display_name = $1,
               organization = $2,
               bio = $3,
               show_on_page = $4,
               updated_at = NOW()
           WHERE user_id = $5`,
          [display_name, organization, bio, show_on_page, userId]
        );
        return { id: existing.rows[0].id, created: false };
      } else {
        const result = await query(
          `INSERT INTO contributors (user_id, display_name, organization, bio, show_on_page, created_at, updated_at)
           VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
           RETURNING id`,
          [userId, display_name, organization, bio, show_on_page]
        );
        return { id: result.rows[0].id, created: true };
      }
    },
  };
}
