/**
 * SQLite data-layer adapter.
 *
 * Exposes the DbAdapter interface (shared/db/interface.js) over the
 * callback-based sqlite3 driver used by the local Express server.
 *
 * Module system: this file uses CommonJS (require/module.exports) so it can
 * be required directly by server.js without any module-system bridging.
 * It does NOT import from the ESM shared/ tree — the ERR_DUPLICATE_USER
 * sentinel is re-declared here to avoid a CJS→ESM require() call, which
 * would need a dynamic import() and complicate the adapter.
 *
 * @module server/adapters/sqliteDb
 */

'use strict';

// Mirror of shared/db/interface.js ERR_DUPLICATE_USER — kept in sync by value.
const ERR_DUPLICATE_USER = 'DUPLICATE_USER';

/**
 * Wrap sqlite3's callback API in promises so the DbAdapter interface is async.
 *
 * @param {import('sqlite3').Database} db - Open sqlite3 database instance
 * @returns {import('../../shared/db/interface.js').DbAdapter}
 */
function makeSqliteAdapter(db) {
  return {
    /**
     * Find a user by username.
     * @param {string} username
     * @returns {Promise<{id: number, username: string, password: string}|null>}
     */
    findUserByUsername(username) {
      return new Promise((resolve, reject) => {
        db.get('SELECT * FROM users WHERE username = ?', [username], (err, row) => {
          if (err) return reject(err);
          resolve(row ?? null);
        });
      });
    },

    /**
     * Create a user.  Translates SQLite's SQLITE_CONSTRAINT_UNIQUE code to
     * ERR_DUPLICATE_USER so the handler core stays driver-agnostic.
     *
     * @param {string} username
     * @param {string} hashedPassword
     * @returns {Promise<{id: number|string, username: string}>}
     */
    createUser(username, hashedPassword) {
      return new Promise((resolve, reject) => {
        db.run(
          'INSERT INTO users (username, password) VALUES (?, ?)',
          [username, hashedPassword],
          function callback(err) {
            if (err) {
              // SQLite unique-constraint error code
              if (err.code === 'SQLITE_CONSTRAINT' || (err.message && err.message.includes('UNIQUE'))) {
                const dupErr = new Error('Username already exists');
                dupErr.code = ERR_DUPLICATE_USER;
                return reject(dupErr);
              }
              return reject(err);
            }
            resolve({ id: this.lastID, username });
          }
        );
      });
    },

    /**
     * List all saved calculations for a user, ordered by date DESC.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listSavedCalcs(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT * FROM calculations WHERE user_id = ? ORDER BY date DESC',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * Insert a new calculation. The timestamp is generated by SQLite
     * via CURRENT_TIMESTAMP — no client-clock date is accepted.
     *
     * @param {number|string} userId
     * @param {{ name, species, product, cost, yield, result }} fields
     * @returns {Promise<{id: number|string}>}
     */
    saveCalc(userId, fields) {
      const { name, species, product, cost, yield: yieldVal, result } = fields;
      return new Promise((resolve, reject) => {
        db.run(
          `INSERT INTO calculations (user_id, name, species, product, cost, yield, result, date)
           VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
          [userId, name, species, product, cost, yieldVal, result],
          function callback(err) {
            if (err) return reject(err);
            resolve({ id: this.lastID });
          }
        );
      });
    },

    /**
     * Find a single calculation by its id. Returns at minimum {id, user_id}.
     *
     * @param {number|string} id
     * @returns {Promise<{id: number, user_id: number}|null>}
     */
    findCalcById(id) {
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id, user_id FROM calculations WHERE id = ?',
          [id],
          (err, row) => {
            if (err) return reject(err);
            resolve(row ?? null);
          }
        );
      });
    },

    /**
     * Delete a calculation by its id.
     * Ownership must be verified by the caller (handler) before calling this.
     *
     * @param {number|string} id
     * @returns {Promise<void>}
     */
    deleteCalc(id) {
      return new Promise((resolve, reject) => {
        db.run('DELETE FROM calculations WHERE id = ?', [id], (err) => {
          if (err) return reject(err);
          resolve();
        });
      });
    },

    // -----------------------------------------------------------------------
    // User-data methods
    // -----------------------------------------------------------------------

    /**
     * List all user_data rows for a user.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listUserData(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT id, species, product, yield, source FROM user_data WHERE user_id = ?',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * Insert a new user_data row.
     *
     * @param {number|string} userId
     * @param {{ species, product, yield, source }} fields
     * @returns {Promise<{id: number|string}>}
     */
    createUserData(userId, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      return new Promise((resolve, reject) => {
        db.run(
          'INSERT INTO user_data (user_id, species, product, yield, source) VALUES (?, ?, ?, ?, ?)',
          [userId, species, product, yieldVal, source],
          function callback(err) {
            if (err) return reject(err);
            resolve({ id: this.lastID });
          }
        );
      });
    },

    /**
     * Find a single user_data row by id. Returns at minimum {id, user_id}.
     *
     * @param {number|string} id
     * @returns {Promise<{id: number, user_id: number}|null>}
     */
    findUserDataById(id) {
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id, user_id FROM user_data WHERE id = ?',
          [id],
          (err, row) => {
            if (err) return reject(err);
            resolve(row ?? null);
          }
        );
      });
    },

    /**
     * Update a user_data row using explicit JS-level fallback for partial updates.
     * The caller (handler) passes null for fields to keep unchanged; this
     * implementation mirrors the production COALESCE behaviour by fetching the
     * existing row first and applying field-level fallback.
     *
     * Ownership must be verified by the caller before this.
     *
     * @param {number|string} id
     * @param {{ species, product, yield, source }} fields  (null = keep current)
     * @returns {Promise<void>}
     */
    updateUserData(id, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      return new Promise((resolve, reject) => {
        // Fetch existing row to apply COALESCE-equivalent fallback
        db.get('SELECT * FROM user_data WHERE id = ?', [id], (getErr, row) => {
          if (getErr) return reject(getErr);
          if (!row) return reject(new Error('Row not found'));

          db.run(
            `UPDATE user_data
             SET species = ?, product = ?, yield = ?, source = ?
             WHERE id = ?`,
            [
              species !== null ? species : row.species,
              product !== null ? product : row.product,
              yieldVal !== null ? yieldVal : row.yield,
              source !== null ? source : row.source,
              id,
            ],
            (err) => {
              if (err) return reject(err);
              resolve();
            }
          );
        });
      });
    },

    /**
     * Delete a user_data row by id.
     * Ownership must be verified by the caller before this.
     *
     * @param {number|string} id
     * @returns {Promise<void>}
     */
    deleteUserData(id) {
      return new Promise((resolve, reject) => {
        db.run('DELETE FROM user_data WHERE id = ?', [id], (err) => {
          if (err) return reject(err);
          resolve();
        });
      });
    },

    /**
     * Upsert one user_data row: update yield+source if (userId, species, product)
     * already exists; otherwise insert.
     *
     * @param {number|string} userId
     * @param {{ species, product, yield, source }} fields
     * @returns {Promise<{inserted: boolean}>}
     */
    upsertUserDataRow(userId, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id FROM user_data WHERE user_id = ? AND LOWER(species) = LOWER(?) AND LOWER(product) = LOWER(?)',
          [userId, species, product],
          (selectErr, existing) => {
            if (selectErr) return reject(selectErr);

            if (existing) {
              db.run(
                'UPDATE user_data SET yield = ?, source = ? WHERE id = ? AND user_id = ?',
                [yieldVal, source, existing.id, userId],
                (updateErr) => {
                  if (updateErr) return reject(updateErr);
                  resolve({ inserted: false });
                }
              );
            } else {
              db.run(
                'INSERT INTO user_data (user_id, species, product, yield, source) VALUES (?, ?, ?, ?, ?)',
                [userId, species, product, yieldVal, source],
                (insertErr) => {
                  if (insertErr) return reject(insertErr);
                  resolve({ inserted: true });
                }
              );
            }
          }
        );
      });
    },

    // -----------------------------------------------------------------------
    // Export methods
    // -----------------------------------------------------------------------

    /**
     * List all user_data rows for export.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listUserDataForExport(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT * FROM user_data WHERE user_id = ?',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * List all calculations for export, ordered by date DESC.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listCalcsForExport(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT * FROM calculations WHERE user_id = ? ORDER BY date DESC',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },
  };
}

module.exports = { makeSqliteAdapter, ERR_DUPLICATE_USER };
