/**
 * SQLite data-layer adapter.
 *
 * Exposes the DbAdapter interface (shared/db/interface.js) over the
 * callback-based sqlite3 driver used by the local Express server.
 *
 * Module system: this file uses CommonJS (require/module.exports) so it can
 * be required directly by server.js without any module-system bridging.
 * It does NOT import from the ESM shared/ tree — the ERR_DUPLICATE_USER
 * sentinel is re-declared here to avoid a CJS→ESM require() call, which
 * would need a dynamic import() and complicate the adapter.
 *
 * @module server/adapters/sqliteDb
 */

'use strict';

// Mirror of shared/db/interface.js ERR_DUPLICATE_USER — kept in sync by value.
const ERR_DUPLICATE_USER = 'DUPLICATE_USER';

/**
 * Wrap sqlite3's callback API in promises so the DbAdapter interface is async.
 *
 * @param {import('sqlite3').Database} db - Open sqlite3 database instance
 * @returns {import('../../shared/db/interface.js').DbAdapter}
 */
function makeSqliteAdapter(db) {
  return {
    /**
     * Find a user by username.
     * @param {string} username
     * @returns {Promise<{id: number, username: string, password: string}|null>}
     */
    findUserByUsername(username) {
      return new Promise((resolve, reject) => {
        db.get('SELECT * FROM users WHERE username = ?', [username], (err, row) => {
          if (err) return reject(err);
          resolve(row ?? null);
        });
      });
    },

    /**
     * Create a user.  Translates SQLite's SQLITE_CONSTRAINT_UNIQUE code to
     * ERR_DUPLICATE_USER so the handler core stays driver-agnostic.
     *
     * @param {string} username
     * @param {string} hashedPassword
     * @returns {Promise<{id: number|string, username: string}>}
     */
    createUser(username, hashedPassword) {
      return new Promise((resolve, reject) => {
        db.run(
          'INSERT INTO users (username, password) VALUES (?, ?)',
          [username, hashedPassword],
          function callback(err) {
            if (err) {
              // SQLite unique-constraint error code
              if (err.code === 'SQLITE_CONSTRAINT' || (err.message && err.message.includes('UNIQUE'))) {
                const dupErr = new Error('Username already exists');
                dupErr.code = ERR_DUPLICATE_USER;
                return reject(dupErr);
              }
              return reject(err);
            }
            resolve({ id: this.lastID, username });
          }
        );
      });
    },

    /**
     * List all saved calculations for a user, ordered by date DESC.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listSavedCalcs(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT * FROM calculations WHERE user_id = ? ORDER BY date DESC',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * Insert a new calculation. The timestamp is generated by SQLite
     * via CURRENT_TIMESTAMP — no client-clock date is accepted.
     *
     * @param {number|string} userId
     * @param {{ name, species, product, cost, yield, result }} fields
     * @returns {Promise<{id: number|string}>}
     */
    saveCalc(userId, fields) {
      const { name, species, product, cost, yield: yieldVal, result } = fields;
      return new Promise((resolve, reject) => {
        db.run(
          `INSERT INTO calculations (user_id, name, species, product, cost, yield, result, date)
           VALUES (?, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)`,
          [userId, name, species, product, cost, yieldVal, result],
          function callback(err) {
            if (err) return reject(err);
            resolve({ id: this.lastID });
          }
        );
      });
    },

    /**
     * Find a single calculation by its id. Returns at minimum {id, user_id}.
     *
     * @param {number|string} id
     * @returns {Promise<{id: number, user_id: number}|null>}
     */
    findCalcById(id) {
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id, user_id FROM calculations WHERE id = ?',
          [id],
          (err, row) => {
            if (err) return reject(err);
            resolve(row ?? null);
          }
        );
      });
    },

    /**
     * Delete a calculation by its id.
     * Ownership must be verified by the caller (handler) before calling this.
     *
     * @param {number|string} id
     * @returns {Promise<void>}
     */
    deleteCalc(id) {
      return new Promise((resolve, reject) => {
        db.run('DELETE FROM calculations WHERE id = ?', [id], (err) => {
          if (err) return reject(err);
          resolve();
        });
      });
    },

    // -----------------------------------------------------------------------
    // User-data methods
    // -----------------------------------------------------------------------

    /**
     * List all user_data rows for a user.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listUserData(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT id, species, product, yield, source FROM user_data WHERE user_id = ?',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * Insert a new user_data row.
     *
     * @param {number|string} userId
     * @param {{ species, product, yield, source }} fields
     * @returns {Promise<{id: number|string}>}
     */
    createUserData(userId, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      return new Promise((resolve, reject) => {
        db.run(
          'INSERT INTO user_data (user_id, species, product, yield, source) VALUES (?, ?, ?, ?, ?)',
          [userId, species, product, yieldVal, source],
          function callback(err) {
            if (err) return reject(err);
            resolve({ id: this.lastID });
          }
        );
      });
    },

    /**
     * Find a single user_data row by id. Returns at minimum {id, user_id}.
     *
     * @param {number|string} id
     * @returns {Promise<{id: number, user_id: number}|null>}
     */
    findUserDataById(id) {
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id, user_id FROM user_data WHERE id = ?',
          [id],
          (err, row) => {
            if (err) return reject(err);
            resolve(row ?? null);
          }
        );
      });
    },

    /**
     * Update a user_data row using explicit JS-level fallback for partial updates.
     * The caller (handler) passes null for fields to keep unchanged; this
     * implementation mirrors the production COALESCE behaviour by fetching the
     * existing row first and applying field-level fallback.
     *
     * Ownership must be verified by the caller before this.
     *
     * @param {number|string} id
     * @param {{ species, product, yield, source }} fields  (null = keep current)
     * @returns {Promise<void>}
     */
    updateUserData(id, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      return new Promise((resolve, reject) => {
        // Fetch existing row to apply COALESCE-equivalent fallback
        db.get('SELECT * FROM user_data WHERE id = ?', [id], (getErr, row) => {
          if (getErr) return reject(getErr);
          if (!row) return reject(new Error('Row not found'));

          db.run(
            `UPDATE user_data
             SET species = ?, product = ?, yield = ?, source = ?
             WHERE id = ?`,
            [
              species !== null ? species : row.species,
              product !== null ? product : row.product,
              yieldVal !== null ? yieldVal : row.yield,
              source !== null ? source : row.source,
              id,
            ],
            (err) => {
              if (err) return reject(err);
              resolve();
            }
          );
        });
      });
    },

    /**
     * Delete a user_data row by id.
     * Ownership must be verified by the caller before this.
     *
     * @param {number|string} id
     * @returns {Promise<void>}
     */
    deleteUserData(id) {
      return new Promise((resolve, reject) => {
        db.run('DELETE FROM user_data WHERE id = ?', [id], (err) => {
          if (err) return reject(err);
          resolve();
        });
      });
    },

    /**
     * Upsert one user_data row: update yield+source if (userId, species, product)
     * already exists; otherwise insert.
     *
     * @param {number|string} userId
     * @param {{ species, product, yield, source }} fields
     * @returns {Promise<{inserted: boolean}>}
     */
    upsertUserDataRow(userId, fields) {
      const { species, product, yield: yieldVal, source } = fields;
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id FROM user_data WHERE user_id = ? AND LOWER(species) = LOWER(?) AND LOWER(product) = LOWER(?)',
          [userId, species, product],
          (selectErr, existing) => {
            if (selectErr) return reject(selectErr);

            if (existing) {
              db.run(
                'UPDATE user_data SET yield = ?, source = ? WHERE id = ? AND user_id = ?',
                [yieldVal, source, existing.id, userId],
                (updateErr) => {
                  if (updateErr) return reject(updateErr);
                  resolve({ inserted: false });
                }
              );
            } else {
              db.run(
                'INSERT INTO user_data (user_id, species, product, yield, source) VALUES (?, ?, ?, ?, ?)',
                [userId, species, product, yieldVal, source],
                (insertErr) => {
                  if (insertErr) return reject(insertErr);
                  resolve({ inserted: true });
                }
              );
            }
          }
        );
      });
    },

    // -----------------------------------------------------------------------
    // Export methods
    // -----------------------------------------------------------------------

    /**
     * List all user_data rows for export.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listUserDataForExport(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT * FROM user_data WHERE user_id = ?',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * List all calculations for export, ordered by date DESC.
     *
     * @param {number|string} userId
     * @returns {Promise<Array>}
     */
    listCalcsForExport(userId) {
      return new Promise((resolve, reject) => {
        db.all(
          'SELECT * FROM calculations WHERE user_id = ? ORDER BY date DESC',
          [userId],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    // -----------------------------------------------------------------------
    // Public methods (no auth)
    // -----------------------------------------------------------------------

    /**
     * List recent public calculations (no user_id), ordered by date DESC,
     * limited to 100 rows.
     *
     * @returns {Promise<Array>}
     */
    listPublicCalcs() {
      return new Promise((resolve, reject) => {
        db.all(
          `SELECT id, species, product, cost, yield, result, date
           FROM calculations
           ORDER BY date DESC
           LIMIT 100`,
          [],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * List all visible contributors joined with username and contribution_count,
     * ordered by contribution_count DESC.
     *
     * @returns {Promise<Array>}
     */
    listContributors() {
      return new Promise((resolve, reject) => {
        db.all(
          `SELECT c.*, u.username, COUNT(ud.id) as contribution_count
           FROM contributors c
           JOIN users u ON c.user_id = u.id
           LEFT JOIN user_data ud ON c.user_id = ud.user_id
           WHERE c.show_on_page = 1
           GROUP BY c.id
           ORDER BY contribution_count DESC`,
          [],
          (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          }
        );
      });
    },

    /**
     * Return the full fish-data payload built from three tables:
     *   species, fish_yields, species_profiles.
     *
     * Note: the local SQLite dev database may not have these tables populated —
     * in that case each query returns empty rows and getFishData returns empty
     * objects.  That is correct local behaviour; the production Neon database
     * holds the imported MAB-37 data.
     *
     * @returns {Promise<{fishData: Object, profiles: Object, source: Object}>}
     */
    getFishData() {
      const allRows = (sql) =>
        new Promise((resolve, reject) => {
          db.all(sql, [], (err, rows) => {
            if (err) return reject(err);
            resolve(rows ?? []);
          });
        });

      return Promise.all([
        allRows('SELECT id, name, scientific_name, category FROM species ORDER BY category, name'),
        allRows('SELECT species_id, from_state, to_state, yield_percent, range_min, range_max FROM fish_yields ORDER BY species_id, from_state, to_state'),
        allRows('SELECT species_id, description, culinary_uses, edible_portions, url FROM species_profiles'),
      ]).then(([speciesRows, yieldRows, profileRows]) => {
        const fishData = {};
        const profiles = {};
        const speciesMap = {};

        for (const species of speciesRows) {
          speciesMap[species.id] = species;
          fishData[species.name] = {
            scientific_name: species.scientific_name,
            category: species.category,
            conversions: {},
          };
        }

        for (const yieldRow of yieldRows) {
          const species = speciesMap[yieldRow.species_id];
          if (species && fishData[species.name]) {
            const fromLabel =
              yieldRow.from_state !== 'Round' &&
              yieldRow.from_state !== 'Whole' &&
              yieldRow.from_state !== 'Raw Whole'
                ? `From ${yieldRow.from_state}: `
                : '';
            const label = `${fromLabel}${yieldRow.to_state}`;
            fishData[species.name].conversions[label] = {
              yield: parseFloat(yieldRow.yield_percent),
              range:
                yieldRow.range_min && yieldRow.range_max
                  ? [parseFloat(yieldRow.range_min), parseFloat(yieldRow.range_max)]
                  : null,
              from: yieldRow.from_state,
              to: yieldRow.to_state,
            };
          }
        }

        for (const profile of profileRows) {
          const species = speciesMap[profile.species_id];
          if (species) {
            profiles[species.name] = {
              description: profile.description,
              culinary_uses: profile.culinary_uses,
              edible_portions: profile.edible_portions,
              url: profile.url,
            };
          }
        }

        return {
          fishData,
          profiles,
          source: {
            title: 'Recoveries and Yields from Pacific Fish and Shellfish',
            authors: ['Chuck Crapo', 'Brian Paust', 'Jerry Babbitt'],
            publisher: 'Alaska Sea Grant College Program',
            publication: 'Marine Advisory Bulletin No. 37',
            year: 2004,
          },
        };
      });
    },

    // -----------------------------------------------------------------------
    // Contributor profile methods (authenticated)
    // -----------------------------------------------------------------------

    /**
     * Return the contributor profile row for userId, or null if none exists.
     *
     * @param {number|string} userId
     * @returns {Promise<Object|null>}
     */
    getContributorProfile(userId) {
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT * FROM contributors WHERE user_id = ?',
          [userId],
          (err, row) => {
            if (err) return reject(err);
            resolve(row ?? null);
          }
        );
      });
    },

    /**
     * Upsert a contributor profile.  Returns {id, created} where created is
     * true for an insert, false for an update.
     *
     * @param {number|string} userId
     * @param {{ display_name, organization, bio, show_on_page }} fields
     * @returns {Promise<{id: number|string, created: boolean}>}
     */
    saveContributorProfile(userId, fields) {
      const { display_name, organization, bio, show_on_page } = fields;
      return new Promise((resolve, reject) => {
        db.get(
          'SELECT id FROM contributors WHERE user_id = ?',
          [userId],
          (selectErr, existing) => {
            if (selectErr) return reject(selectErr);

            const now = new Date().toISOString();
            if (existing) {
              db.run(
                `UPDATE contributors
                 SET display_name = ?, organization = ?, bio = ?, show_on_page = ?, updated_at = ?
                 WHERE user_id = ?`,
                [display_name, organization, bio, show_on_page ? 1 : 0, now, userId],
                (updateErr) => {
                  if (updateErr) return reject(updateErr);
                  resolve({ id: existing.id, created: false });
                }
              );
            } else {
              db.run(
                `INSERT INTO contributors (user_id, display_name, organization, bio, show_on_page, created_at, updated_at)
                 VALUES (?, ?, ?, ?, ?, ?, ?)`,
                [userId, display_name, organization, bio, show_on_page ? 1 : 0, now, now],
                function callback(insertErr) {
                  if (insertErr) return reject(insertErr);
                  resolve({ id: this.lastID, created: true });
                }
              );
            }
          }
        );
      });
    },
  };
}

module.exports = { makeSqliteAdapter, ERR_DUPLICATE_USER };
