/**
 * Data-layer interface for the handler core.
 *
 * Both the SQLite adapter (server/) and the Neon adapter (api/) expose this
 * same shape so handler logic never depends on a specific driver.
 *
 * @module shared/db/interface
 */

/**
 * @typedef {Object} DbUser
 * @property {number|string} id
 * @property {string} username
 */

/**
 * @typedef {Object} DbCalc
 * @property {number|string} id
 * @property {number|string} user_id
 * @property {string}        [name]
 * @property {string}        [species]
 * @property {string}        [product]
 * @property {number}        [cost]
 * @property {number}        [yield]
 * @property {string}        [result]
 * @property {string}        [date]  - ISO timestamp, generated by the database
 */

/**
 * @typedef {Object} DbAdapter
 *
 * @property {function(string): Promise<DbUser|null>} findUserByUsername
 *   Return the user row matching username, or null if not found.
 *
 * @property {function(string, string): Promise<DbUser>} createUser
 *   Insert a new user (username, hashedPassword) and return {id, username}.
 *   Throws an error with code 'DUPLICATE_USER' when the username is already
 *   taken (adapters normalise driver-specific constraint codes to this value).
 *
 * @property {function(string|number): Promise<DbCalc[]>} listSavedCalcs
 *   Return all calculations for the given userId, ordered by date DESC.
 *
 * @property {function(string|number, Object): Promise<{id: string|number}>} saveCalc
 *   Insert a new calculation (userId, {name, species, product, cost, yield, result}).
 *   The date/timestamp is generated by the database — do not accept a client timestamp.
 *   Returns {id} of the inserted row.
 *
 * @property {function(string|number): Promise<DbCalc|null>} findCalcById
 *   Return the calculation row for the given id, or null if not found.
 *   Returns at minimum {id, user_id} for ownership checking.
 *
 * @property {function(string|number): Promise<void>} deleteCalc
 *   Delete the calculation with the given id.
 *   The caller (handler) is responsible for ownership checks before calling this.
 *
 * @property {function(): Promise<DbCalc[]>} listPublicCalcs
 *   Return public calculation rows for the unauthenticated community feed.
 *   Must omit user_id and other private user fields.
 *
 * @property {function(): Promise<Object>} getFishData
 *   Return the fish-data payload consumed by the frontend:
 *   {fishData, profiles, source}.
 *
 * @property {function(): Promise<Array>} listContributors
 *   Return visible contributor profiles plus contribution_count.
 *
 * @property {function(string|number): Promise<Object|null>} getContributorProfile
 *   Return the authenticated user's contributor profile, or null if none exists.
 *
 * @property {function(string|number, Object): Promise<{id?: string|number, created: boolean}>} saveContributorProfile
 *   Create or update the authenticated user's contributor profile.
 *
 * @property {function(string|number): Promise<Array>} listUserData
 *   Return all custom yield rows owned by the user.
 *
 * @property {function(string|number, Object): Promise<{id: string|number}>} createUserData
 *   Insert one custom yield row for the user.
 *
 * @property {function(string|number): Promise<Object|null>} findUserDataById
 *   Return a custom yield row by id, including user_id for ownership checks.
 *
 * @property {function(string|number, string|number, Object): Promise<void>} updateUserData
 *   Update one owned custom yield row.
 *
 * @property {function(string|number, string|number): Promise<void>} deleteUserData
 *   Delete one owned custom yield row.
 *
 * @property {function(string|number, Array): Promise<{inserted: number, updated: number}>} upsertUserDataRows
 *   Transactionally upsert normalized upload rows for the user.
 *
 * @property {function(string|number): Promise<Array>} listExportUserData
 *   Return custom yield rows for CSV export.
 *
 * @property {function(string|number): Promise<Array>} listExportCalcs
 *   Return saved calculation rows for CSV export.
 */

/**
 * Sentinel error code thrown by createUser when username is already taken.
 * Adapters translate driver-specific constraint codes (e.g. SQLite SQLITE_CONSTRAINT,
 * Postgres 23505) to this value so the handler core stays transport-agnostic.
 *
 * @constant {string}
 */
export const ERR_DUPLICATE_USER = 'DUPLICATE_USER';
