/**
 * Data-layer interface for the handler core.
 *
 * Both the SQLite adapter (server/) and the Neon adapter (api/) expose this
 * same shape so handler logic never depends on a specific driver.
 *
 * @module shared/db/interface
 */

/**
 * @typedef {Object} DbUser
 * @property {number|string} id
 * @property {string} username
 */

/**
 * @typedef {Object} DbCalc
 * @property {number|string} id
 * @property {number|string} user_id
 * @property {string}        [name]
 * @property {string}        [species]
 * @property {string}        [product]
 * @property {number}        [cost]
 * @property {number}        [yield]
 * @property {string}        [result]
 * @property {string}        [date]  - ISO timestamp, generated by the database
 */

/**
 * @typedef {Object} DbAdapter
 *
 * @property {function(string): Promise<DbUser|null>} findUserByUsername
 *   Return the user row matching username, or null if not found.
 *
 * @property {function(string, string): Promise<DbUser>} createUser
 *   Insert a new user (username, hashedPassword) and return {id, username}.
 *   Throws an error with code 'DUPLICATE_USER' when the username is already
 *   taken (adapters normalise driver-specific constraint codes to this value).
 *
 * @property {function(string|number): Promise<DbCalc[]>} listSavedCalcs
 *   Return all calculations for the given userId, ordered by date DESC.
 *
 * @property {function(string|number, Object): Promise<{id: string|number}>} saveCalc
 *   Insert a new calculation (userId, {name, species, product, cost, yield, result}).
 *   The date/timestamp is generated by the database — do not accept a client timestamp.
 *   Returns {id} of the inserted row.
 *
 * @property {function(string|number): Promise<DbCalc|null>} findCalcById
 *   Return the calculation row for the given id, or null if not found.
 *   Returns at minimum {id, user_id} for ownership checking.
 *
 * @property {function(string|number): Promise<void>} deleteCalc
 *   Delete the calculation with the given id.
 *   The caller (handler) is responsible for ownership checks before calling this.
 */

/**
 * Sentinel error code thrown by createUser when username is already taken.
 * Adapters translate driver-specific constraint codes (e.g. SQLite SQLITE_CONSTRAINT,
 * Postgres 23505) to this value so the handler core stays transport-agnostic.
 *
 * @constant {string}
 */
export const ERR_DUPLICATE_USER = 'DUPLICATE_USER';
