/**
 * Data-layer interface for the handler core.
 *
 * Both the SQLite adapter (server/) and the Neon adapter (api/) expose this
 * same shape so handler logic never depends on a specific driver.
 *
 * @module shared/db/interface
 */

/**
 * @typedef {Object} DbUser
 * @property {number|string} id
 * @property {string} username
 */

/**
 * @typedef {Object} DbCalc
 * @property {number|string} id
 * @property {number|string} user_id
 * @property {string}        [name]
 * @property {string}        [species]
 * @property {string}        [product]
 * @property {number}        [cost]
 * @property {number}        [yield]
 * @property {string}        [result]
 * @property {string}        [date]  - ISO timestamp, generated by the database
 */

/**
 * @typedef {Object} DbAdapter
 *
 * @property {function(string): Promise<DbUser|null>} findUserByUsername
 *   Return the user row matching username, or null if not found.
 *
 * @property {function(string, string): Promise<DbUser>} createUser
 *   Insert a new user (username, hashedPassword) and return {id, username}.
 *   Throws an error with code 'DUPLICATE_USER' when the username is already
 *   taken (adapters normalise driver-specific constraint codes to this value).
 *
 * @property {function(string|number): Promise<DbCalc[]>} listSavedCalcs
 *   Return all calculations for the given userId, ordered by date DESC.
 *
 * @property {function(string|number, Object): Promise<{id: string|number}>} saveCalc
 *   Insert a new calculation (userId, {name, species, product, cost, yield, result}).
 *   The date/timestamp is generated by the database — do not accept a client timestamp.
 *   Returns {id} of the inserted row.
 *
 * @property {function(string|number): Promise<DbCalc|null>} findCalcById
 *   Return the calculation row for the given id, or null if not found.
 *   Returns at minimum {id, user_id} for ownership checking.
 *
 * @property {function(string|number): Promise<void>} deleteCalc
 *   Delete the calculation with the given id.
 *   The caller (handler) is responsible for ownership checks before calling this.
 *
 * @property {function(string|number): Promise<DbUserData[]>} listUserData
 *   Return all user_data rows for the given userId.
 *
 * @property {function(string|number, {species, product, yield, source}): Promise<{id: string|number}>} createUserData
 *   Insert a new user_data row and return {id}.
 *
 * @property {function(string|number): Promise<DbUserData|null>} findUserDataById
 *   Return the user_data row for the given id, or null if not found.
 *   Returns at minimum {id, user_id} for ownership checking.
 *
 * @property {function(string|number, {species, product, yield, source}): Promise<void>} updateUserData
 *   Update a user_data row.  The adapter uses COALESCE so undefined fields keep
 *   their current value.  Ownership must be verified by the caller before this.
 *
 * @property {function(string|number): Promise<void>} deleteUserData
 *   Delete the user_data row with the given id.
 *   Ownership must be verified by the caller before this.
 *
 * @property {function(string|number, {species, product, yield, source}): Promise<{inserted: boolean}>} upsertUserDataRow
 *   Upsert one row: if a row with matching (userId, species, product) already
 *   exists update its yield+source; otherwise insert.
 *   Returns {inserted: true} for a new row, {inserted: false} for an update.
 *
 * @property {function(string|number): Promise<DbUserData[]>} listUserDataForExport
 *   Return all user_data rows for the given userId (for CSV export).
 *
 * @property {function(string|number): Promise<DbCalc[]>} listCalcsForExport
 *   Return all calculation rows for the given userId ordered by date DESC
 *   (for CSV export).
 *
 * @property {function(): Promise<DbCalc[]>} listPublicCalcs
 *   Return recent calculations without user_id, ordered by date DESC, limited
 *   to 100 rows.  No auth required — caller passes no userId.
 *
 * @property {function(): Promise<DbContributor[]>} listContributors
 *   Return all contributor rows where show_on_page is true, joined with
 *   username and contribution_count, ordered by contribution_count DESC.
 *
 * @property {function(): Promise<{fishData: Object, profiles: Object, source: Object}>} getFishData
 *   Return the full fish-data payload: species keyed by name (with conversions),
 *   profiles keyed by name, and the MAB-37 source citation object.
 *
 * @property {function(string|number): Promise<DbContributor|null>} getContributorProfile
 *   Return the contributor row for userId, or null if none exists.
 *
 * @property {function(string|number, {display_name, organization, bio, show_on_page}): Promise<{id: string|number, created: boolean}>} saveContributorProfile
 *   Upsert a contributor profile for userId.
 *   Returns {id, created: true} on insert, {id, created: false} on update.
 */

/**
 * @typedef {Object} DbUserData
 * @property {number|string} id
 * @property {number|string} user_id
 * @property {string}        species
 * @property {string}        product
 * @property {number}        yield
 * @property {string}        [source]
 */

/**
 * @typedef {Object} DbContributor
 * @property {number|string} id
 * @property {number|string} user_id
 * @property {string}        [display_name]
 * @property {string}        [organization]
 * @property {string}        [bio]
 * @property {boolean|number} show_on_page
 * @property {string}        [created_at]
 * @property {string}        [updated_at]
 */

/**
 * Sentinel error code thrown by createUser when username is already taken.
 * Adapters translate driver-specific constraint codes (e.g. SQLite SQLITE_CONSTRAINT,
 * Postgres 23505) to this value so the handler core stays transport-agnostic.
 *
 * @constant {string}
 */
export const ERR_DUPLICATE_USER = 'DUPLICATE_USER';
