/**
 * Transport-agnostic saved-calculations handlers.
 *
 * Three handlers live here because they share the same domain object and
 * DbAdapter methods:
 *   - handleListSavedCalcs  — GET /api/saved-calcs
 *   - handleSaveCalc        — POST /api/save-calc
 *   - handleDeleteCalc      — DELETE /api/saved-calcs/:id
 *
 * All three require an authenticated user. Adapters extract the user id from
 * the token and pass it as `input.userId` — the handler never touches HTTP
 * headers or JWT parsing.
 *
 * Ownership enforcement (a user can only read/delete their own calculations)
 * lives here in the handler core so both backends enforce it identically.
 *
 * Drift resolved from the dual-backend state:
 *   - Timestamps generated by the database (no client-clock toISOString()).
 *   - Sanitized error responses — raw driver messages never reach the caller.
 *   - Delete endpoint missing from both backends — added here, wired in both.
 *   - Ownership check on delete enforced in the handler (was absent from both).
 *
 * @module shared/handlers/savedCalcs
 */

// ---------------------------------------------------------------------------
// List saved calculations
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} ListSavedCalcsRequest
 * @property {string|number} userId  - From the verified JWT / adapter
 */

/**
 * @typedef {Object} ListSavedCalcsResponse
 * @property {number}   status
 * @property {Object}   body
 * @property {Array}    [body]        Array of calculation rows on success
 * @property {string}   [body.error]  Present on failure
 */

/**
 * List all saved calculations for the authenticated user.
 *
 * @param {ListSavedCalcsRequest} input
 * @param {import('../db/interface.js').DbAdapter} db
 * @returns {Promise<ListSavedCalcsResponse>}
 */
export async function handleListSavedCalcs(input, db) {
  const { userId } = input;

  if (!userId) {
    return { status: 401, body: { error: 'Unauthorized' } };
  }

  try {
    const rows = await db.listSavedCalcs(userId);
    return { status: 200, body: rows };
  } catch (err) {
    console.error('[list-saved-calcs] unexpected error:', err.message ?? err);
    return { status: 500, body: { error: 'Failed to fetch calculations' } };
  }
}

// ---------------------------------------------------------------------------
// Save a calculation
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} SaveCalcRequest
 * @property {string|number} userId   - From the verified JWT / adapter
 * @property {unknown}       [name]
 * @property {unknown}       [species]
 * @property {unknown}       [product]
 * @property {unknown}       [cost]
 * @property {unknown}       [yield]
 * @property {unknown}       [result]
 */

/**
 * @typedef {Object} SaveCalcResponse
 * @property {number}          status
 * @property {Object}          body
 * @property {string|number}   [body.id]       Present on success
 * @property {string}          [body.message]  Present on success
 * @property {string}          [body.error]    Present on failure
 */

/**
 * Save a new calculation for the authenticated user.
 * The date/timestamp is generated by the database — no client clock used.
 *
 * @param {SaveCalcRequest} input
 * @param {import('../db/interface.js').DbAdapter} db
 * @returns {Promise<SaveCalcResponse>}
 */
export async function handleSaveCalc(input, db) {
  const { userId, name, species, product, cost, yield: yieldVal, result } = input;

  if (!userId) {
    return { status: 401, body: { error: 'Unauthorized' } };
  }

  try {
    const row = await db.saveCalc(userId, { name, species, product, cost, yield: yieldVal, result });
    return {
      status: 201,
      body: { id: row.id, message: 'Calculation saved successfully' },
    };
  } catch (err) {
    console.error('[save-calc] unexpected error:', err.message ?? err);
    return { status: 500, body: { error: 'Failed to save calculation' } };
  }
}

// ---------------------------------------------------------------------------
// Delete a calculation
// ---------------------------------------------------------------------------

/**
 * @typedef {Object} DeleteCalcRequest
 * @property {string|number} userId  - From the verified JWT / adapter
 * @property {unknown}       [id]    - Calculation id from route param
 */

/**
 * @typedef {Object} DeleteCalcResponse
 * @property {number}  status
 * @property {Object}  body
 * @property {string}  [body.message]  Present on success
 * @property {string}  [body.error]    Present on failure
 */

/**
 * Delete a calculation owned by the authenticated user.
 * Ownership is enforced in the handler: a user cannot delete another user's calc.
 *
 * @param {DeleteCalcRequest} input
 * @param {import('../db/interface.js').DbAdapter} db
 * @returns {Promise<DeleteCalcResponse>}
 */
export async function handleDeleteCalc(input, db) {
  const { userId, id } = input;

  if (!userId) {
    return { status: 401, body: { error: 'Unauthorized' } };
  }

  const calcId = Number(id);
  if (!id || Number.isNaN(calcId)) {
    return { status: 400, body: { error: 'Invalid calculation id' } };
  }

  try {
    // Fetch the calc first to enforce ownership
    const calc = await db.findCalcById(calcId);

    if (!calc) {
      return { status: 404, body: { error: 'Calculation not found' } };
    }

    // Ownership check — compare as strings to handle int vs string id types
    if (String(calc.user_id) !== String(userId)) {
      return { status: 403, body: { error: 'Forbidden' } };
    }

    await db.deleteCalc(calcId);
    return { status: 200, body: { message: 'Calculation deleted' } };
  } catch (err) {
    console.error('[delete-calc] unexpected error:', err.message ?? err);
    return { status: 500, body: { error: 'Failed to delete calculation' } };
  }
}
